  

  nginx_$NAME:
    image: nginx:1.15.5-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/home/app/server/static
      - ./media:/home/app/server/media
    labels:
      - "traefik.frontend.rule=Host:$REVERSE_PROXY_HOST"
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s